METHOD_ATTRIBUTE = 'method'
PARAMS_ATTRIBUTE = 'params'
MISSING_PARAMS_ATTRIBUTE = 'missing_params'
USER_ATTRIBUTE = 'user'
REPLY_ATTRIBUTE = 'reply_to_user'
REQUEST_ATTRIBUTE = 'requests'
USER_LANGUAGE_ATTRIBUTE = 'user_language'
#IS_CONFIRMED = 'confirm'