default_model: gemini_fast

api_keys:
    gemini : '123' ##change these values with your actual api_key
    gemini2: 'aa'
    huggingface: 'bc'


models:
  gemini_generic:
    provider: gemini
    
  gemini_fast:
    provider: gemini
    model_name: "gemini-2.5-flash"
    api_key: gemini2

  gemini_pro:
    provider: gemini
    model_name: "gemini-2.5-pro"
    api_key: '1234'

  hf_mistral:
    provider: huggingface
    model_name: "mistralai/Mistral-7B-Instruct-v0.3"